In [12]:
from absenteeism_module import *

In [13]:
# pd.read_csv('Absenteeism_data_new.csv')

In [14]:
model = absenteeism_model('model','scaler')

In [15]:

model.load_and_clean_data('Absenteeism_data_new.csv')

In [16]:
model.predicted_outputs()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Probability,Prediction
0,0,0,0,1,7,289,33,30,0,2,1,0.590824,1
1,0,0,0,0,7,118,50,31,0,1,0,0.076129,0
2,0,0,0,1,7,179,38,31,0,0,0,0.250964,0
3,1,0,0,0,7,279,39,24,0,2,0,0.872194,1
4,0,0,0,1,7,289,33,30,0,2,1,0.590824,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,1,0,0,0,5,179,40,22,1,2,0,0.633559,1
696,1,0,0,0,5,225,28,24,0,1,2,0.698509,1
697,1,0,0,0,5,330,28,25,1,0,0,0.860247,1
698,0,0,0,1,5,235,32,25,1,0,0,0.246343,0
699,0,0,0,1,5,291,40,25,0,1,1,0.369566,0